      - name: 🔨 Kompile Firmware
        run: |
          rm -f Yoefie_Family_Switch.ino
          arduino-cli compile --fqbn esp32:esp32:esp32 esp32-firmware-builder.ino --output-dir ./build

      - name: 📤 Upload .bin ke Hosting via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          port: 21
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: build/
          server-dir: /public_html/firmware/

      - name: ✅ Selesai
        run: |
          echo "✅ Berhasil! File tersedia di: https://smart.yoefiefamily.biz.id/firmware/"
